# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='users_locations',
        ),
        migrations.AddField(
            model_name='location',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.Session'),
            preserve_default=False,
        ),
    ]
