# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-17 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20180712_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Session'),
        ),
    ]
